local function AddMaterial(path)
	return resource.AddFile(string.format("materials/yawd/%s", path))
end

AddMaterial("no_power.png")
AddMaterial("portal_spark.vmt")
AddMaterial("spike.png")
AddMaterial("trap_area.png")

AddMaterial("base_images/trap_bae.png")
AddMaterial("base_images/trap_side.png")
AddMaterial("base_images/trap_spike.png")
AddMaterial("base_images/trap_tar.png")

AddMaterial("hud/ammo_box.png")
AddMaterial("hud/blade_trap.png")
AddMaterial("hud/core.png")
AddMaterial("hud/crusher.png")
AddMaterial("hud/explosive.png")
AddMaterial("hud/floor_turret.png")
AddMaterial("hud/lava.png")
AddMaterial("hud/lightning_rod.png")
AddMaterial("hud/spikes.png")
AddMaterial("hud/steam_trap.png")
AddMaterial("hud/tar.png")
AddMaterial("hud/icon_sheet.png")
AddMaterial("hud/icon_sheet_overlay.png")

AddMaterial("models/trap_base.vmt")
AddMaterial("models/trap_blade.vmt")
AddMaterial("models/trap_blade_selfillum.vmt")
AddMaterial("models/trap_crusher.vmt")
AddMaterial("models/trap_crusher_part.vmt")
AddMaterial("models/trap_lava.vmt")
AddMaterial("models/trap_lava_empty.vmt")
AddMaterial("models/trap_lava_selfillum.vtf")
AddMaterial("models/trap_lightning.vtf")
AddMaterial("models/trap_push.vmt")
AddMaterial("models/trap_side.vmt")
AddMaterial("models/trap_spike.vmt")
AddMaterial("models/trap_squre.vmt")
AddMaterial("models/trap_tar.vmt")

resource.AddFile("materials/entities/wep_build.png")
resource.AddFile("materials/entities/yawd_fists.png")
resource.AddFile("materials/entities/yawd_fists_extreme.png")
resource.AddFile("materials/entities/yawd_lmg.png")
resource.AddFile("materials/entities/yawd_pistol.png")
resource.AddFile("materials/entities/yawd_rifle.png")
resource.AddFile("materials/entities/yawd_shotgun.png")
resource.AddFile("materials/entities/yawd_sniper.png")
